### ISSUE TITLE
Desktop Support

### ISSUE THREAD

**Issue by Nandanrmenon** [rsoft-in/scrawl#5]
Regarding desktop releases, I am confused whether to do implement local database or not. Since the default plugins don't work, desktop needs a another plugin to run ```sqflite```.
I am also thinking to implement a syncing services, although the syncing service will be closed source. We might end up giving the source code but services will be closed. App UI design in under work. After the back-end is done, desktop development will soon start.

**Comment by altrepo2022** [comment]
@Nandanrmenon  Hello, what about using drift instead of sqflite?

**Comment by Nandanrmenon** [comment]
Support added
